<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="shortcut icon" href="<?= $this->baseUrl(); ?>/img/favicon.ico" type="image/x-icon">
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl(); ?>/css/app.css" media="all">
        <title>Aveo Auris Consil</title>
        <script type="text/javascript" src="<?= $this->baseUrl(); ?>/js/jquery-1.8.2.min.js"></script>  
        <script type="text/javascript" src="<?= $this->baseUrl(); ?>/js/jquery-ui-1.9.1.custom.min.js"></script>  
        <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
        <script type="text/javascript" src="<?= $this->baseUrl(); ?>/js/kickstart.js"></script>                                  <!-- KICKSTART -->
        <script type="text/javascript" src="<?= $this->baseUrl(); ?>/js/utility.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl(); ?>/js/audio.js"></script>   
        <script type="text/javascript" src="<?= $this->baseUrl(); ?>/js/bootstrap-typeahead.js"></script>
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl(); ?>/css/kickstart.css" media="all" />                  <!-- KICKSTART -->
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl(); ?>/css/style.css" media="all" />                     <!-- CUSTOM STYLES -->
        <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl(); ?>/css/jquery-ui-1.9.1.custom.css" media="all" />
    </head>
    <body>
        <a id="top-of-page">&nbsp;</a>
        <div id="wrap" class="clearfix">
            <div style="padding: 10px;">
                <a id="logo" href="<?= $this->baseUrl(); ?>">
                    <img src="<?= $this->baseUrl(); ?>/img/logo1s.png" alt="Aveo Auris Consil">
                </a>
            </div>
            <?php echo $this->navigation()->menu()->setUlClass('menu'); ?>
            <div class="col_12 right">
                <br />
                <?php 
                    if(Scitotec_Utilities::getSessionKunde() != 0) {
                        $oKunde = new Application_Model_Kunde();
                        $mKunde = new Application_Model_KundeMapper();
                        $mKunde->find(Scitotec_Utilities::getSessionKunde(),$oKunde);
                        echo '<span class="icon small green" data-icon="u"></span> &nbsp;'. $oKunde->getVorname()." ".$oKunde->getNachname();
                    }
                ?>
            </div>
            <div class="col_12">
                <?php echo $this->layout()->content ?>
            </div>
            <div id="file_container" class="col_12">
            	<?php echo $this->action("index", "datei", "default", Zend_Controller_Front::getInstance()->getRequest()->getParams()); ?>
            </div>
            <div class="clear"></div>
            <div id="footer">
                &copy; Copyright 2012 Aveo Auris Consil <a href="<?= $this->baseUrl(); ?>/erstberatung/impressum">Impressum</a>. Diese WebApp wurde von der<a href="http://www.scitotec.com">Scitotec GmbH</a> erstellt.
                <a id="link-top" href="#top-of-page">Top</a>
            </div>
        </div>
    </body>
</html>